source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2’
use_frameworks!

target ‘mhml’ do
    pod 'Alamofire', '~> 4.3'
    pod 'Pushy', '1.0.5'
    pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
