# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLBlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAccData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RawGSRData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('gsr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RawHRData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('hr', models.FloatField()),
                ('rr', models.FloatField()),
                ('mode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RawTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
