# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLBlock', '0002_auto_20170131_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawaccdata',
            name='X',
        ),
        migrations.RemoveField(
            model_name='rawaccdata',
            name='Y',
        ),
        migrations.RemoveField(
            model_name='rawaccdata',
            name='Z',
        ),
        migrations.RemoveField(
            model_name='rawaccdata',
            name='time',
        ),
        migrations.RemoveField(
            model_name='rawgsrdata',
            name='gsr',
        ),
        migrations.RemoveField(
            model_name='rawgsrdata',
            name='time',
        ),
        migrations.RemoveField(
            model_name='rawhrdata',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='rawhrdata',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='rawhrdata',
            name='rr',
        ),
        migrations.RemoveField(
            model_name='rawhrdata',
            name='time',
        ),
        migrations.RemoveField(
            model_name='rawtempdata',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='rawtempdata',
            name='time',
        ),
        migrations.AddField(
            model_name='rawaccdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rawgsrdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rawhrdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rawtempdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
